/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookstore.gui;

import com.mycompany.bookstore.util.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ALFAZAIRI
 */
public class BooksTableFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BooksTableFrame.class.getName());

    /**
     * Creates new form BooksTableFrame
     */

    public BooksTableFrame() {
    initComponents();
     setupAutoID(); 
}
private void setupAutoID() {
    DefaultTableModel model = (DefaultTableModel) booksTable.getModel();

    int titleCol = 1;  
    int authorCol = 2; 
    int idCol = 0;     

    model.addTableModelListener(e -> {
        int row = e.getFirstRow();
        int col = e.getColumn();

        if(col == titleCol || col == authorCol){
            Object idObj = model.getValueAt(row, idCol);
            String currentID = idObj == null ? "" : idObj.toString();

            // لو BookID فاضي فقط، نولّد ID جديد
            if(currentID.isEmpty()) {
                String title = (String) model.getValueAt(row, titleCol);
                String author = (String) model.getValueAt(row, authorCol);

                if(title != null && !title.isEmpty() && author != null && !author.isEmpty()){
                    String id = "BK-" + title.substring(0,1).toUpperCase()
                                     + author.substring(0,1).toUpperCase()
                                     + "-" + System.currentTimeMillis() % 10000;

                    model.setValueAt(id, row, idCol);
                }
            }
        }
    });
}





    DefaultTableModel model = new DefaultTableModel(
        new String[]{"BookID", "Title", "Author", "Genre", "Price"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return true; 
        }

    };

  






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Id", "Author", "price", "quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BookId", "Title", "Author", "Genre", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(booksTable);

        jButton1.setText("Save changes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) booksTable.getModel();

    try (Connection con = DBConnection.getConnection()) {
        con.setAutoCommit(false);

        String updateQuery = "UPDATE Book SET Title=?, Author=?, Genre=?, Price=? WHERE BookID=?";
        String insertQuery = "INSERT INTO Book(BookID, Title, Author, Genre, Price) VALUES(?,?,?,?,?)";

    
        PreparedStatement psUpdate = con.prepareStatement(updateQuery);
        PreparedStatement psInsert = con.prepareStatement(insertQuery);

        for (int i = 0; i < model.getRowCount(); i++) {
            Object idObj = model.getValueAt(i, 0);
            String bookID = idObj == null ? "" : idObj.toString().trim();

            String title  = model.getValueAt(i, 1) == null ? "" : model.getValueAt(i, 1).toString();
            String author = model.getValueAt(i, 2) == null ? "" : model.getValueAt(i, 2).toString();
            String genre  = model.getValueAt(i, 3) == null ? "" : model.getValueAt(i, 3).toString();
            double price  = model.getValueAt(i, 4) == null ? 0 : Double.parseDouble(model.getValueAt(i, 4).toString());

            if(bookID.isEmpty()) {
                // توليد ID جديد إذا مفيش
                bookID = "BK-" + System.currentTimeMillis();
                model.setValueAt(bookID, i, 0);

                psInsert.setString(1, bookID);
                psInsert.setString(2, title);
                psInsert.setString(3, author);
                psInsert.setString(4, genre);
                psInsert.setDouble(5, price);
                psInsert.executeUpdate();
            } else {
                psUpdate.setString(1, title);
                psUpdate.setString(2, author);
                psUpdate.setString(3, genre);
                psUpdate.setDouble(4, price);
                psUpdate.setString(5, bookID);
                psUpdate.executeUpdate();
            }
        }

        con.commit();
        JOptionPane.showMessageDialog(this, "Changes saved successfully!");

        // جلب البيانات بعد الحفظ
        loadBooksTable();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }




    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new AdminFrame().setVisible(true);  
           this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BooksTableFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable booksTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public JTable getBooksTable() {
    return booksTable;
    
}

void loadBooksTable() {
    try (Connection con = DBConnection.getConnection();
         PreparedStatement ps = con.prepareStatement("SELECT * FROM Book");
         ResultSet rs = ps.executeQuery()) {

        DefaultTableModel model = (DefaultTableModel) booksTable.getModel();
        model.setRowCount(0); // فضّي الجدول قبل التحميل

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("BookID"),
                rs.getString("Title"),
                rs.getString("Author"),
                rs.getString("Genre"),
                rs.getDouble("Price")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}
}

