/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bookstore.gui;

import com.mycompany.bookstore.Session.Session;
import com.mycompany.bookstore.daoImp.BookDAOimp;
import com.mycompany.bookstore.model.Book;
import com.mycompany.bookstore.model.Customer;
import com.mycompany.bookstore.model.OrderItems;
import com.mycompany.bookstore.model.Orders;
import com.mycompany.bookstore.service.OrdersService;
import com.mycompany.bookstore.util.DBConnection;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFAZAIRI
 */
public class CreateOrderFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateOrderFrame.class.getName());

   public CreateOrderFrame() {
        initComponents();
        clearEmptyRows();
        addQuantityListener();     


    }

    public CreateOrderFrame(String bookId, int qty) {
        initComponents();
        clearEmptyRows();
        addBookToTable(bookId, qty);
        calculateTotal();
        addQuantityListener();
    }


    private void clearEmptyRows() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }

    private void addBookToTable(String bookId, int qty) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        BookDAOimp bookDAO = new BookDAOimp(DBConnection.getConnection());
        String title = bookDAO.getBookTitleById(bookId);
BigDecimal priceBD = bookDAO.getBookPriceById(bookId);
double price = priceBD.doubleValue();

        double total = price * qty;

        model.addRow(new Object[]{
            bookId,
            title,
            price,
            qty,
            total
        });
    }

    private void updateTotalPrice() {
    double grandTotal = 0;
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {

        Object priceObj = model.getValueAt(i, 2); // Price
        Object qtyObj   = model.getValueAt(i, 3); // Quantity

        if (priceObj != null && qtyObj != null) {

            double price = Double.parseDouble(priceObj.toString());
            int qty = Integer.parseInt(qtyObj.toString());

            double rowTotal = price * qty;
            model.setValueAt(rowTotal, i, 4);

            grandTotal += rowTotal;
        }
    }

    jLabel3.setText("Total Price: " + grandTotal + " LE");
}

    
    private void calculateTotal() {
        double sum = 0;
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            Object val = model.getValueAt(i, 4); // Total column
            if (val != null) {
                sum += Double.parseDouble(val.toString());
            }
        }
        jLabel3.setText("Total Price: " + sum + " LE");
    }


    
   
   private void addQuantityListener() {
    jTable1.getModel().addTableModelListener(e -> {
        if (e.getColumn() == 3) { // Quantity
            updateTotalPrice();
        }
    });
}

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BookId", "Title", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Shipping Address:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Payment Method:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card" }));

        jLabel3.setText("Total Price: 0 LE");

        jButton1.setText("Confirm Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(15, 15, 15)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addGap(104, 104, 104)
                        .addComponent(jButton2)))
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//
//    if (model.getRowCount() == 0) {
//        JOptionPane.showMessageDialog(this, "No books in order");
//        return;
//    }
//
//    if (jTextField1.getText().trim().isEmpty()) {
//        JOptionPane.showMessageDialog(this, "Please enter shipping address");
//        return;
//    }
//
//    JOptionPane.showMessageDialog(this, "Order placed successfully ✅");
//    this.dispose(); // يقفل الفريم بعد التأكيد
//}

    try {
        // 1️⃣ إنشاء الأوردر
        Orders order = new Orders();
        order.setOrderDate(java.time.LocalDate.now());
        order.setPaymentStatus(
                jComboBox1.getSelectedItem().toString()
        );

        // 2️⃣ تحديد اليوزر 
        Customer customer = Session.getCurrentCustomer();

if (customer == null) {
    JOptionPane.showMessageDialog(this, "Please login first");
    return;
}

order.setCustomer(customer);


        // 3️⃣ قراءة بيانات الجدول
        DefaultTableModel model =
                (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            Object bookIdObj = model.getValueAt(i, 0);
            Object priceObj  = model.getValueAt(i, 2);
            Object qtyObj    = model.getValueAt(i, 3);

            if (bookIdObj == null) continue;

            OrderItems item = new OrderItems();
//            item.setBookId(bookIdObj.toString());
            Book book = new Book();
             book.setBookId(bookIdObj.toString());
            item.setBook(book);

            item.setQuantity(Integer.parseInt(qtyObj.toString()));

            BigDecimal price = new BigDecimal(priceObj.toString());
            BigDecimal qty   = new BigDecimal(qtyObj.toString());
            item.setTotalPrice(price.multiply(qty));
            item.setOrder(order); 
            order.addOrderItem(item);
        }

        // 4️⃣ حفظ في الداتابيز
        OrdersService service =
                new OrdersService(DBConnection.getConnection());
        service.placeOrder(order);

        JOptionPane.showMessageDialog(this,
                "Order placed successfully ✔");

        // 5️⃣ تنظيف / إغلاق
        this.dispose();

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Error while placing order: " + ex.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//    int choice = JOptionPane.showConfirmDialog(
//        this,
//        "Are you sure you want to cancel the order?",
//        "Confirm",
//        JOptionPane.YES_NO_OPTION
//    );
//
//    if (choice == JOptionPane.YES_OPTION) {
//        this.dispose();
//    }
//}

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to cancel?",
            "Cancel Order",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        this.dispose();
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateOrderFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
