
package com.mycompany.bookstore.gui;

import com.mycompany.bookstore.util.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALFAZAIRI
 */
public class CustomerTableFrame extends javax.swing.JFrame {
    private int editingRow = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerTableFrame.class.getName());

    /**
     * Creates new form CustomerTableFrame
     */
    public CustomerTableFrame() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel(
    new Object[][]{},
    new String[]{"User ID", "First Name", "Last Name", "Address", "Communication Preference"}
) {
    @Override
    public boolean isCellEditable(int row, int column) {
        // UserID دايمًا مقفول
        if (column == 0) return false;

        Object userID = getValueAt(row, 0);

        // صف جديد (لسه ما اتحفظش) مسموح بالتعديل
        if (userID == null || userID.toString().trim().isEmpty()) return true;

        // صف محفوظ → مسموح التعديل بس لو في Update Mode
        return row == editingRow;
    }
};

customerTable.setModel(model);
loadCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID ", "First Name", "Last Name", "Adress", "Communication Prefrence"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerTable);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) customerTable.getModel();  
    model.addRow(new Object[]{null, "", "", "", ""});

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

    DefaultTableModel model = (DefaultTableModel) customerTable.getModel();

try (Connection con = DBConnection.getConnection()) {
    con.setAutoCommit(false);

    String insertUser = "INSERT INTO Users(FirstName, LastName, PhoneNumber, Email, UserName, PasswordHash, UserType) VALUES (?, ?, ?, ?, ?, ?, ?)";
    String insertCustomer = "INSERT INTO Customer(UserID, CustomerAddress, CommunicationPrefrence) VALUES (?, ?, ?)";

    PreparedStatement psUser = con.prepareStatement(insertUser, PreparedStatement.RETURN_GENERATED_KEYS);
    PreparedStatement psCustomer = con.prepareStatement(insertCustomer);

    for (int i = 0; i < model.getRowCount(); i++) {

        Integer userID = (Integer) model.getValueAt(i, 0);
        String firstName = (String) model.getValueAt(i, 1);
        String lastName = (String) model.getValueAt(i, 2);
        String address = (String) model.getValueAt(i, 3);
        String commPref = (String) model.getValueAt(i, 4);

        // لو User قديم.. متعملش Insert تاني
        if (userID != null) {
            continue;
        }

        psUser.setString(1, firstName);
        psUser.setString(2, lastName);
        psUser.setString(3, "N/A");
        psUser.setString(4, firstName + "@gmail.com"); // لازم ايميل مختلف
        psUser.setString(5, "user_" + firstName + "_" + i);
        psUser.setString(6, "default");
        psUser.setString(7, "Customer");
        psUser.executeUpdate();

        // هات الـ userID الجديد
        ResultSet rs = psUser.getGeneratedKeys();
        int newID = 0;
        if (rs.next()) {
            newID = rs.getInt(1);
        }

        // Insert في Customer
        psCustomer.setInt(1, newID);
        psCustomer.setString(2, address);
        psCustomer.setString(3, commPref);
        psCustomer.executeUpdate();
    }

    con.commit();

    // refresh
    model.setRowCount(0);
    loadCustomers();

    JOptionPane.showMessageDialog(this, "Saved successfully!");

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error while saving!");
}

editingRow = -1; 
customerTable.repaint();



    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new AdminFrame().setVisible(true);  
           this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    int row = customerTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "choose a customer to update");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
    Object userID = model.getValueAt(row, 0);

    if (userID == null || userID.toString().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "This customer hasn't been saved yet");
        return;
    }

    editingRow = row;
    customerTable.repaint();

    JOptionPane.showMessageDialog(this, "✏️ update data then click save");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    int row = customerTable.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "choose a customer to delete");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
    Object userIDObj = model.getValueAt(row, 0);

    if (userIDObj == null || userIDObj.toString().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "This customer hasn't been saved yet");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure to delete this customer?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    int userID = Integer.parseInt(userIDObj.toString());

    try (Connection con = DBConnection.getConnection()) {
        // أولًا نحذف من Customer
        PreparedStatement ps1 = con.prepareStatement("DELETE FROM Customer WHERE UserID=?");
        ps1.setInt(1, userID);
        ps1.executeUpdate();

        // بعدين نحذف من Users
        PreparedStatement ps2 = con.prepareStatement("DELETE FROM Users WHERE UserID=?");
        ps2.setInt(1, userID);
        ps2.executeUpdate();

        model.removeRow(row);
        JOptionPane.showMessageDialog(this, "🗑️ Deleted successfully");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerTableFrame().setVisible(true));
    }
   
    private void loadCustomers() {
    DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
    model.setRowCount(0);

    String query = "SELECT u.UserID, u.FirstName, u.LastName, c.CustomerAddress, c.CommunicationPrefrence " +
                   "FROM Users u INNER JOIN Customer c ON u.UserID = c.UserID " +
                   "WHERE u.UserType = 'Customer'";

    try (Connection con = DBConnection.getConnection();
         PreparedStatement ps = con.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("UserID"),
                rs.getString("FirstName"),
                rs.getString("LastName"),
                rs.getString("CustomerAddress"),
                rs.getString("CommunicationPrefrence")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading customers!");
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
